//
// Created by Magnus on 3/31/21.
//
#pragma once
#ifndef NULL
#define NULL 0
#endif
#include "queue.h"

struct IntegerSlistType {
    int data;
    SLIST_ENTRY(IntegerSlistType) entries;             /* Singly linked list */
};

SLIST_HEAD(mySinglyLinkedList, IntegerSlistType);

struct IntegerSTAILQueueType {
    int val;
    STAILQ_ENTRY(IntegerSTAILQueueType) links;
};

STAILQ_HEAD(mySTAILQueue, IntegerSTAILQueueType);

//When inlining the functions, no coverage was generated by gcov. Maybe solvable
//but it shouldn't affect functionality only performance.
IntegerSlistType* SLIST_FIRST_impl(mySinglyLinkedList* h);

void STAILQ_INIT_impl(mySTAILQueue* head);
bool STAILQ_EMPTY_impl(mySTAILQueue *head);
void STAILQ_INSERT_HEAD_impl(mySTAILQueue* head, IntegerSTAILQueueType* entry);
void STAILQ_REMOVE_HEAD_impl(mySTAILQueue* head);